### ISSUE TITLE
fix lỗi  Invalid argument và get link 320

### ISSUE THREAD

**Issue by Vipdt5k49** [ndkhoa200400/nct-downloader#1]
hi bạn,

mình có góp ý sau:
- lỗi  Invalid argument: do Track.track_name có ký tự ? ==> có thể dùng slugify chuẩn hóa lại tên
from slugify import slugify
...
file_name = "nhac/" + slugify(self.track_name) + ".mp3"

- get link 320 trước
bạn code thêm để ưu tiên get link 320 (thẻ locationHQ) trước 128(location) 

Thank bạn

**Comment by ndkhoa200400** [comment]
Cám ơn bạn đã feedback. Mình sẽ lên bản fix và cải thiện

**Comment by ndkhoa200400** [comment]
Chào bạn,
Mình đã fix lỗi ` Invalid argument` và mình cũng support download nhạc HQ
Cám ơn bạn đã raise issue 💯
